### ISSUE TITLE
System.InvalidOperationException: SeedMachines.Framework.BigCraftables.SeedBandit cannot be serialized because it does not have a parameterless constructor.

### ISSUE THREAD

**Issue by mrveress** [mrveress/SDVMods#2]
After seeing any event (e.g. Junimos activating Greenhouse) something to do with the constructor not having a parameterless version.

System.InvalidOperationException: SeedMachines.Framework.BigCraftables.SeedBandit cannot be serialized because it does not have a parameterless constructor.

**My assumption** 
So, logic of the game for custom object is temp replacing of native GameObject with my custom instance of GameObject-child class. 

Events:
OnDayStarted - inject custom in current location
OnWarped - inject custom in current location
OnObjectListChanged - inject custom in current location
OnDayEnding - revert to standard in all locations

Seems need to handle another smapi event for additional reverting the items to standard GameObject class.

**Comment by darkphoenixff4** [comment]
Hey, I'm the one who reported this.  I can likely help out with pointing you in the direction of the problem.

StardewValley.Object has this constructor:
`public Object()
    {
    }`

I think the problem is that none of your classes that extend it have a similar constructor; all the constructors require at least two parameters.  As a result, the serializer crashes because if I had to guess, it does `new (name of class)();` and then sets the properties from the XML on the outside.

**Comment by mrveress** [comment]
Will pack those changes and will upload it to nexus. I'll check the changes today evening, now have no time. @darkphoenixff4 if you will have ability to test it too - it would be perfect. And thanks again for your help and attention to this issue)

**Comment by mrveress** [comment]
@darkphoenixff4 just checked with first Junimo event (building bridge) and saving in that day - seems working fine now, so I'll close the request for now. Thanks again for your help!)
